const data = {
  products: [
    {
      id: 1,
      name: 'Nike air',
      slug: 'Nike slim',
      catagory: 'Shoe',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'original brand new shoes',
    },
    {
      id: 2,
      name: 'Nike jordan',
      slug: 'Nike slim',
      catagory: 'Shirt',
      image: '/images/p2.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'original brand new shoes',
    },
    {
      id: 3,
      name: 'Nike',
      slug: 'Nike slim',
      catagory: 'Shoe',
      image: '/images/p3.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'original brand new shoes',
    },
    {
      id: 4,
      name: 'Nike latest',
      slug: 'Nike slim',
      catagory: 'Shoe',
      image: '/images/p4.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'original brand new shoes',
    },
  ],
};

export default data;
